DELPHIPATH=~/Desktop/20200212_delphi
export PYTHONPATH=$PYTHONPATH:$DELPHIPATH/IW2D/PYTHON_codes_and_scripts/General_Python_tools/
export PYTHONPATH=$PYTHONPATH:$DELPHIPATH/IW2D/PYTHON_codes_and_scripts/Impedance_lib_Python/
export PYTHONPATH=$PYTHONPATH:$DELPHIPATH/DELPHI/DELPHI_Python
export PYTHONPATH=$PYTHONPATH:$DELPHIPATH/DELPHI/DELPHI

echo "PYTHONPATH="
echo $PYTHONPATH
